# Generated by Django 3.2.2 on 2021-05-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210523_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='dp.jpeg', null=True, upload_to='accounts/'),
        ),
    ]
